import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const divs = [];
  for (let i = 0; i < 20; i++) {
    divs.push(
      <div key={i} className="w-screen h-12 border-b border-slate-800"></div>
    );
  }

  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ height: "100%", overflow: "auto" }}
      >
        <div className="w-screen h-24 bg-slate-800"></div>
        <div className="divs-container" style={{ position: "relative" }}>
          {divs}
          <div
            className="children-container"
            style={{ position: "absolute", top: 0 }}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
